#!/usr/bin/env python3
"""
Generate a per-title kernel ordinal remap for xbox_kernel_set_ordinal_remap.

    py -3 -m tools.kernel_audit.gen_ordinal_remap <analysis.json> --out remap.h

The kernel bridge routes ordinals with one hardcoded table -- the ordinal ABI of
the XDK it was written against. A title built with a different XDK numbers the
same functions differently (Burnout 3's XDK 5849 has HalRequestSoftwareInterrupt
at 49 where the older XDKs have HalReturnToFirmware). The kernel functions are
the same; only the ordinal that names each differs.

This maps a title's ordinals into the kernel's canonical space by NAME: for each
kernel function the title imports, look up which ordinal the kernel's own table
gives that function, and emit `map[title_ordinal] = canonical_ordinal` where they
differ. Names the title's parser could not resolve, or that the kernel's table
does not have, are left identity and reported -- a title that never calls them
boots regardless, and one that does surfaces a real gap rather than a silent
misroute.

The output is a C header a title includes and hands to
xbox_kernel_set_ordinal_remap before xbox_kernel_bridge_init.
"""

import argparse
import json
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
PARSER_PY = os.path.join(ROOT, "tools", "xbe_parser", "xbe_parser.py")


def canonical_name_to_ordinal():
    """The kernel's own ordinal ABI, name -> ordinal (from KERNEL_EXPORTS)."""
    src = open(PARSER_PY, encoding="utf-8", errors="replace").read()
    m = re.search(r"KERNEL_EXPORTS\s*[:=][^{]*\{(.*?)\n\}", src, re.S)
    assert m, "could not locate KERNEL_EXPORTS in tools/xbe_parser"
    out = {}
    for o, n in re.findall(r"(\d+)\s*:\s*[\"']([A-Za-z_][A-Za-z0-9_]*)", m.group(1)):
        out.setdefault(n, int(o))   # first wins; ordinals are unique anyway
    return out


def build_remap(analysis_path):
    imports = json.load(open(analysis_path))["kernel_imports"]
    canon = canonical_name_to_ordinal()
    remap = {}          # title_ordinal -> canonical_ordinal (only where differ)
    identity = 0
    unresolved = []     # (ordinal, name) the title imports but we cannot map
    for imp in imports:
        o, name = imp["ordinal"], imp["name"]
        if not name or name.startswith("Unknown_"):
            unresolved.append((o, name or "?"))
            continue
        tgt = canon.get(name)
        if tgt is None:
            unresolved.append((o, name))
            continue
        if tgt == o:
            identity += 1
        else:
            remap[o] = tgt
    return remap, identity, unresolved, len(imports)


def emit_header(remap, out_path, title, analysis_path):
    hi = max(remap) if remap else 0
    guard = "XBOX_ORDINAL_REMAP_H"
    lines = [
        "/* Generated by tools/kernel_audit/gen_ordinal_remap.py -- do not edit.",
        " * Per-title kernel ordinal remap for xbox_kernel_set_ordinal_remap.",
        " * Source: %s" % os.path.basename(analysis_path),
        " * Title : %s" % title,
        " *",
        " * map[title_ordinal] = canonical_ordinal; 0 = identity.",
        " */",
        "#ifndef %s" % guard,
        "#define %s" % guard,
        "",
        "static const unsigned short g_xbox_ordinal_remap[%d] = {" % (hi + 1),
    ]
    row = "   "
    for o in range(hi + 1):
        row += " %3d," % remap.get(o, 0)
        if (o + 1) % 12 == 0:
            lines.append(row)
            row = "   "
    if row.strip():
        lines.append(row)
    lines += [
        "};",
        "#define XBOX_ORDINAL_REMAP_COUNT %d" % (hi + 1),
        "",
        "#endif /* %s */" % guard,
        "",
    ]
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    open(out_path, "w").write("\n".join(lines))


def main(argv=None):
    ap = argparse.ArgumentParser(prog="tools.kernel_audit.gen_ordinal_remap",
                                 description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("analysis", help="analysis.json from tools.xbe_parser")
    ap.add_argument("--out", required=True, help="C header to write")
    args = ap.parse_args(argv)

    data = json.load(open(args.analysis))
    title = data.get("title", os.path.basename(args.analysis))
    remap, identity, unresolved, total = build_remap(args.analysis)

    emit_header(remap, args.out, title, args.analysis)

    print("%s -- %d kernel imports" % (title, total))
    print("  identity (XDK matches kernel) : %d" % identity)
    print("  remapped (same name, diff ord): %d" % len(remap))
    print("  unresolved (left identity)    : %d" % len(unresolved))
    for o, n in unresolved:
        print("      ordinal %d  %s" % (o, n))
    print("  wrote %s" % args.out)
    if not remap:
        print("  (no remap needed -- this title's XDK matches the kernel;"
              " it need not call xbox_kernel_set_ordinal_remap)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
