"""
Replace XDK library functions by name instead of lifting them.

The DOAXBV port reached gameplay by replacing D3D8 at its API and translating
to D3D11, never emulating the GPU underneath. It found each D3D8 function by a
hard-coded address, which makes the replacement one game's. Here the address
comes from tools.xdk_symbols (XbSymbolDatabase signatures), and the
replacement is keyed by the XDK function's *name*, so one implementation of
D3DDevice_SetTexture serves every title whose XDK build the database covers.

Mechanism, reusing what the recompiler already does for hand-written code:

  * an implemented name's address joins the `manual` set, so its body is not
    lifted and every direct call routes through the runtime lookup;
  * a generated `recomp_hle.c` defines that address's `sub_XXXXXXXX` as a
    thunk that calls `hle_<Name>` and then pops the stack.

The thunk, not the implementation, pops the stack, and the count comes from
the original function's own `ret N`. The signature database's parameter lists
are right for 311 of the 314 D3D8 and DirectSound functions checked against
the lifted code in Burnout 2 -- and wrong for three, which would leave esp off
in every caller. The binary cannot be wrong about what it pops.

Implementations mark themselves with `HLE_EXPORT(Name)`; this module scans for
that marker the way manual_scan scans recomp_manual.c, so the list of what is
replaced cannot drift from what is written.
"""

import glob
import json
import os
import re

EXPORT_RE = re.compile(r"^\s*HLE_EXPORT\(\s*([A-Za-z_]\w*)\s*\)", re.M)


def implemented_names(paths):
    """Names marked HLE_EXPORT(...) in the given C files or directories."""
    names = set()
    for path in paths:
        files = (glob.glob(os.path.join(path, "**", "*.c"), recursive=True)
                 if os.path.isdir(path) else [path])
        for f in files:
            with open(f, encoding="utf-8", errors="replace") as fh:
                names.update(EXPORT_RE.findall(fh.read()))
    return names


def load_symbols(path):
    """Function symbols from a tools.xdk_symbols JSON file."""
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    return [s for s in data.get("symbols", []) if s.get("kind") == "function"]


def stack_cleanup(code, start_va):
    """Bytes of arguments a function's `ret` pops, or None if unknowable.

    Linear sweep over the function's bytes. Every `ret` must agree: a
    function with two different counts, or no `ret` at all (it leaves only by
    tail jumps), has no single number a thunk could use.
    """
    from capstone import Cs, CS_ARCH_X86, CS_MODE_32

    md = Cs(CS_ARCH_X86, CS_MODE_32)
    pops = set()
    for insn in md.disasm(code, start_va):
        if insn.mnemonic == "ret":
            pops.add(int(insn.op_str, 0) if insn.op_str else 0)
    return pops.pop() if len(pops) == 1 else None


def plan(symbols, implemented, known_addrs, manual, cleanup):
    """Decide which addresses to replace.

    `cleanup(addr)` returns the argument bytes that function's `ret` pops, or
    None. Returns (replace, notes): `replace` maps address -> (name, pop);
    `notes` lists why an implemented name was not used, so a silent miss is
    visible.
    """
    replace, notes = {}, []
    by_name = {}
    for s in symbols:
        by_name.setdefault(s["name"], []).append(s["address"])
    for name in sorted(implemented):
        addrs = by_name.get(name)
        if not addrs:
            notes.append(f"{name}: not found in this XBE")
            continue
        if len(addrs) > 1:
            # Two addresses for one name means the signature matched twice;
            # replacing either would be a guess.
            notes.append(f"{name}: {len(addrs)} matches, skipped")
            continue
        addr = addrs[0]
        if addr in manual:
            notes.append(f"{name}: 0x{addr:08X} is hand-written in the title, "
                         "which wins")
            continue
        if addr not in known_addrs:
            notes.append(f"{name}: 0x{addr:08X} is not a detected function")
            continue
        pop = cleanup(addr)
        if pop is None:
            notes.append(f"{name}: 0x{addr:08X} has no single `ret N`, skipped")
            continue
        replace[addr] = (name, pop)
    return replace, notes


def render_thunks(replace):
    """C source defining each replaced sub_XXXXXXXX as a thunk to hle_<Name>.

    The thunk pops the return address the caller pushed plus the argument
    bytes the original `ret N` popped, exactly as the lifted body would have.
    """
    lines = [
        "/* Generated by tools.recomp from the title's XDK symbols.",
        " * Each XDK function below is replaced by name: the lifted body is not",
        " * generated, and the address's sub_XXXXXXXX calls hle_<Name>, then",
        " * pops what the original function's own `ret N` popped. */",
        '#include "recomp_types.h"',
        "",
    ]
    for addr, (name, _) in sorted(replace.items()):
        lines.append(f"void hle_{name}(void);")
    lines.append("")
    for addr, (name, pop) in sorted(replace.items()):
        # g_esp, not esp: `esp` is a shorthand local to each lifted chunk,
        # while recomp_types.h declares the real register for every file.
        lines.append(f"void sub_{addr:08X}(void) {{ hle_{name}(); g_esp += {4 + pop}; }}"
                     f"  /* {name}, ret {pop} */")
    lines.append("")
    return "\n".join(lines)
